application: zinc-shard-358
version: 5
runtime: python27
api_version: 1
threadsafe: no

handlers:

- url: /images
  static_dir: images

- url: /css
  static_dir: css

- url: /js
  static_dir: js

- url: /static
  static_dir: static

- url: /favicon\.ico
  static_files: static/favicon.ico
  upload: static/favicon.ico  

- url: /robots\.txt
  static_files: static/robots.txt
  upload: static/robots.txt

- url: /sitemap\.xml
  static_files: static/sitemap.xml
  upload: static/sitemap.xml

# web-starter-kit
- url: /fonts
  static_dir: static/web-starter-kit/app/fonts

# devfest site
- url: /devfest/
  static_files: static/devfest/index.html
  upload: static/devfest/index.html

- url: /devfest/(.*)/$
  static_files: static/devfest/\1/index.html
  upload: static/devfest/(.*)/index.html

- url: /devfest
  static_dir: static/devfest

# cron job
- url: /cron/gplus
  script: main.app
  login: admin

- url: /.*
  script: main.app

libraries:
- name: jinja2
  version: latest

- name: webapp2
  version: "2.5.1"
